# Generated by Django 5.1.1 on 2024-10-16 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_video', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('dificuldade', models.IntegerField()),
                ('historia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historias.historia')),
            ],
        ),
        migrations.CreateModel(
            name='CriancaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correto', models.BooleanField()),
                ('tempo_resolucao', models.TimeField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'atividades',
            },
        ),
    ]
