# Generated by Django 5.1.1 on 2024-09-29 20:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(validators=[users.models.validate_age]),
        ),
    ]
